In [ ]:
!pip install SeqMetrics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting SeqMetrics
  Downloading SeqMetrics-1.3.3.tar.gz (33 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from SeqMetrics) (1.21.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from SeqMetrics) (1.7.3)
Building wheels for collected packages: SeqMetrics
  Building wheel for SeqMetrics (setup.py) ... done
  Created wheel for SeqMetrics: filename=SeqMetrics-1.3.3-py3-none-any.whl size=32796 sha256=9bc310daeb4ce8961dd80c52f27ac4be696c01a6e9706c0ae55885fda962791c
  Stored in directory: /root/.cache/pip/wheels/81/46/2d/18ccdecfd266cbb7db61df0b43e25cbd047d5aea74b0b8a22f
Successfully built SeqMetrics
Installing collected packages: SeqMetrics
Successfully installed SeqMetrics-1.3.3

In [ ]:
import numpy as np
import pandas as pd

from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

from SeqMetrics import RegressionMetrics

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/IAConcentracion2/Copia de 2012_2019_PlatteRiverWeir_features_merged_all.csv')
df

,SensorTime,CaptureTime,Filename,Agency,SiteNumber,TimeZone,Stage,Discharge,CalcTimestamp,width,...,WeirPt2X,WeirPt2Y,WwRawLineMin,WwRawLineMax,WwRawLineMean,WwRawLineSigma,WwCurveLineMin,WwCurveLineMax,WwCurveLineMean,WwCurveLineSigma
0,2012-06-09 13:15:00,2012-06-09T13:09:07,StateLineWeir_20120609_Farrell_001.jpg,USGS,6674500,MDT,2.99,916.0,2020-03-11T16:58:28,4288,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
1,2012-06-09 13:15:00,2012-06-09T13:10:29,StateLineWeir_20120609_Farrell_002.jpg,USGS,6674500,MDT,2.99,916.0,2020-03-11T16:58:33,4288,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2,2012-06-09 13:45:00,2012-06-09T13:44:01,StateLineWeir_20120609_Farrell_003.jpg,USGS,6674500,MDT,2.96,873.0,2020-03-11T16:58:40,4288,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
3,2012-06-09 14:45:00,2012-06-09T14:44:30,StateLineWeir_20120609_Farrell_004.jpg,USGS,6674500,MDT,2.94,846.0,2020-03-11T16:58:47,4288,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
4,2012-06-09 15:45:00,2012-06-09T15:44:59,StateLineWeir_20120609_Farrell_005.jpg,USGS,6674500,MDT,2.94,846.0,2020-03-11T16:58:55,4288,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42054,2019-10-11 09:00:00,2019-10-11T08:59:53,StateLineWeir_20191011_Farrell_409.jpg,USGS,6674500,MDT,2.54,434.0,2020-03-12T16:23:53,4288,...,2446,1900,9284.0,77521.0,38385.370066,15952.029728,0.0,70085.0,37550.894823,16444.401209
42055,2019-10-11 10:00:00,2019-10-11T09:59:52,StateLineWeir_20191011_Farrell_410.jpg,USGS,6674500,MDT,2.54,434.0,2020-03-12T16:23:54,4288,...,2440,1900,10092.0,74614.0,40162.989292,15467.708856,0.0,70061.0,39397.339095,16009.008049
42056,2019-10-11 11:00:00,2019-10-11T10:59:52,StateLineWeir_20191011_Farrell_411.jpg,USGS,6674500,MDT,2.54,434.0,2020-03-12T16:23:55,4288,...,2447,1900,7067.0,83260.0,42095.946590,16770.357949,0.0,76335.0,41350.006568,17489.374617
42057,2019-10-11 12:00:00,2019-10-11T11:59:53,StateLineWeir_20191011_Farrell_412.jpg,USGS,6674500,MDT,2.54,434.0,2020-03-12T16:23:56,4288,...,2443,1900,6283.0,83045.0,45345.490954,17498.432849,0.0,78882.0,44553.920296,18268.294896
42058,2019-10-11 12:45:00,2019-10-11T12:59:52,StateLineWeir_20191011_Farrell_413.jpg,USGS,6674500,MDT,2.54,434.0,2020-03-12T16:23:58,4288,...,2436,1900,7375.0,89813.0,47877.870782,19963.166359,0.0,82630.0,47280.270559,20559.358767

In [ ]:
df.columns = ['SensorTime', 'CaptureTime', 'Filename', 'Agency', 'SiteNumber',
       'TimeZone', 'Stage', 'Discharge', 'CalcTimestamp', 'width',
       'height', 'exposure', 'fNumber', 'isoSpeed', 'shutterSpeed',
       'grayMean', 'graySigma', 'entropyMean', 'entropySigma', 'hMean',
       'hSigma', 'sMean', 'sSigma', 'vMean', 'vSigma', 'areaFeatCount',
       'grayMean 0', 'graySigma 0', 'entropyMean 0', 'entropySigma 0',
       'hMean 0', 'hSigma 0', 'sMean 0', 'sSigma 0', 'vMean 0',
       'vSigma 0', 'grayMean 1', 'graySigma 1', 'entropyMean 1',
       'entropySigma 1', 'hMean 1', 'hSigma 1', 'sMean 1', 'sSigma 1',
       'vMean 1', 'vSigma 1', 'WeirAngle', 'WeirPt1X', 'WeirPt1Y',
       'WeirPt2X', 'WeirPt2Y', 'WwRawLineMin', 'WwRawLineMax',
       'WwRawLineMean', 'WwRawLineSigma', 'WwCurveLineMin',
       'WwCurveLineMax', 'WwCurveLineMean', 'WwCurveLineSigma']

df = df.drop(['Filename', 'Agency', 'SiteNumber','TimeZone'],axis=1)
df

,SensorTime,CaptureTime,Stage,Discharge,CalcTimestamp,width,height,exposure,fNumber,isoSpeed,...,WeirPt2X,WeirPt2Y,WwRawLineMin,WwRawLineMax,WwRawLineMean,WwRawLineSigma,WwCurveLineMin,WwCurveLineMax,WwCurveLineMean,WwCurveLineSigma
0,2012-06-09 13:15:00,2012-06-09T13:09:07,2.99,916.0,2020-03-11T16:58:28,4288,2848,0.000250,4.0,200,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
1,2012-06-09 13:15:00,2012-06-09T13:10:29,2.99,916.0,2020-03-11T16:58:33,4288,2848,0.000312,4.0,200,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2,2012-06-09 13:45:00,2012-06-09T13:44:01,2.96,873.0,2020-03-11T16:58:40,4288,2848,0.000312,4.0,200,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
3,2012-06-09 14:45:00,2012-06-09T14:44:30,2.94,846.0,2020-03-11T16:58:47,4288,2848,0.000312,4.0,200,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
4,2012-06-09 15:45:00,2012-06-09T15:44:59,2.94,846.0,2020-03-11T16:58:55,4288,2848,0.000312,4.0,200,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42054,2019-10-11 09:00:00,2019-10-11T08:59:53,2.54,434.0,2020-03-12T16:23:53,4288,2848,0.000312,4.0,200,...,2446,1900,9284.0,77521.0,38385.370066,15952.029728,0.0,70085.0,37550.894823,16444.401209
42055,2019-10-11 10:00:00,2019-10-11T09:59:52,2.54,434.0,2020-03-12T16:23:54,4288,2848,0.000250,4.0,200,...,2440,1900,10092.0,74614.0,40162.989292,15467.708856,0.0,70061.0,39397.339095,16009.008049
42056,2019-10-11 11:00:00,2019-10-11T10:59:52,2.54,434.0,2020-03-12T16:23:55,4288,2848,0.000250,4.0,200,...,2447,1900,7067.0,83260.0,42095.946590,16770.357949,0.0,76335.0,41350.006568,17489.374617
42057,2019-10-11 12:00:00,2019-10-11T11:59:53,2.54,434.0,2020-03-12T16:23:56,4288,2848,0.000312,4.0,200,...,2443,1900,6283.0,83045.0,45345.490954,17498.432849,0.0,78882.0,44553.920296,18268.294896
42058,2019-10-11 12:45:00,2019-10-11T12:59:52,2.54,434.0,2020-03-12T16:23:58,4288,2848,0.000400,4.0,200,...,2436,1900,7375.0,89813.0,47877.870782,19963.166359,0.0,82630.0,47280.270559,20559.358767

In [ ]:
df = df.drop(['SensorTime', 'CaptureTime',  'CalcTimestamp'],axis=1)
df

,Stage,Discharge,width,height,exposure,fNumber,isoSpeed,shutterSpeed,grayMean,graySigma,...,WeirPt2X,WeirPt2Y,WwRawLineMin,WwRawLineMax,WwRawLineMean,WwRawLineSigma,WwCurveLineMin,WwCurveLineMax,WwCurveLineMean,WwCurveLineSigma
0,2.99,916.0,4288,2848,0.000250,4.0,200,-1.0,97.405096,39.623303,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
1,2.99,916.0,4288,2848,0.000312,4.0,200,-1.0,104.066757,40.179745,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
2,2.96,873.0,4288,2848,0.000312,4.0,200,-1.0,105.636831,40.533218,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
3,2.94,846.0,4288,2848,0.000312,4.0,200,-1.0,104.418949,41.752678,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
4,2.94,846.0,4288,2848,0.000312,4.0,200,-1.0,106.763541,44.442097,...,-1,-1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42054,2.54,434.0,4288,2848,0.000312,4.0,200,-1.0,82.872720,57.702652,...,2446,1900,9284.0,77521.0,38385.370066,15952.029728,0.0,70085.0,37550.894823,16444.401209
42055,2.54,434.0,4288,2848,0.000250,4.0,200,-1.0,89.028383,55.840861,...,2440,1900,10092.0,74614.0,40162.989292,15467.708856,0.0,70061.0,39397.339095,16009.008049
42056,2.54,434.0,4288,2848,0.000250,4.0,200,-1.0,94.722097,54.355753,...,2447,1900,7067.0,83260.0,42095.946590,16770.357949,0.0,76335.0,41350.006568,17489.374617
42057,2.54,434.0,4288,2848,0.000312,4.0,200,-1.0,96.693270,52.787629,...,2443,1900,6283.0,83045.0,45345.490954,17498.432849,0.0,78882.0,44553.920296,18268.294896
42058,2.54,434.0,4288,2848,0.000400,4.0,200,-1.0,98.738399,52.025453,...,2436,1900,7375.0,89813.0,47877.870782,19963.166359,0.0,82630.0,47280.270559,20559.358767

In [ ]:
mlp = MLPRegressor() #hidden_layer_sizes=(2,),activation='logistic',alpha=0.01
mlp.fit(df.drop(['Stage','Discharge'],axis=1),df[['Stage','Discharge']])

y_predMLP = mlp.predict(df.drop(['Stage','Discharge'],axis=1))

In [ ]:
y_predMLP = pd.DataFrame(y_predMLP,columns=['Stage','Discharge'])
y_predMLP

           Stage    Discharge
0       3.085181  3570.765029
1       3.719583  3624.924895
2       3.599155  3562.516014
3       3.637211  3559.986848
4       4.263305  3614.812808
...          ...          ...
42054  10.347496   585.854864
42055  24.004327   467.926944
42056  16.767648   567.959311
42057  27.010680   550.073578
42058  30.449636   465.019281

[42059 rows x 2 columns]

In [ ]:
erMLPS_S = RegressionMetrics(df['Stage'], y_predMLP['Stage'])
erMLP_D = RegressionMetrics(df['Discharge'], y_predMLP['Discharge'])

In [ ]:
svr_S = SVR()
svr_D = SVR()

svr_S.fit(df.drop(['Stage','Discharge'],axis=1),df['Stage'])
svr_D.fit(df.drop(['Stage','Discharge'],axis=1),df['Discharge'])

y_predSVR_S = svr_S.predict(df.drop(['Stage','Discharge'],axis=1))
y_predSVR_D = svr_D.predict(df.drop(['Stage','Discharge'],axis=1))

In [ ]:
y_predSVR = pd.DataFrame({'Stage':y_predSVR_S,'Discharge':y_predSVR_D})
y_predSVR

          Stage   Discharge
0      3.283983  856.700519
1      3.284260  856.701055
2      3.284464  856.701392
3      3.284612  856.701592
4      3.284859  856.702005
...         ...         ...
42054  2.748666  473.053954
42055  2.764495  483.148533
42056  2.791338  589.615320
42057  2.855480  655.072845
42058  3.060889  771.963612

[42059 rows x 2 columns]

In [ ]:
erSVR_S = RegressionMetrics(df['Stage'], y_predSVR['Stage'])
erSVR_D = RegressionMetrics(df['Discharge'], y_predSVR['Discharge'])

In [ ]:
rfr = RandomForestRegressor()
rfr.fit(df.drop(['Stage','Discharge'],axis=1),df[['Stage','Discharge']])
y_predRFR = rfr.predict(df.drop(['Stage','Discharge'],axis=1))

In [ ]:
y_predRFR = pd.DataFrame(y_predRFR,columns=['Stage','Discharge'])
y_predRFR

        Stage  Discharge
0      3.1358   1152.480
1      3.1513   1167.480
2      3.0659   1061.970
3      3.0190    986.850
4      3.0118    960.100
...       ...        ...
42054  2.5594    453.460
42055  2.5160    414.480
42056  2.5908    497.618
42057  2.6204    526.580
42058  2.6442    549.420

[42059 rows x 2 columns]

In [ ]:
erRFR_S = RegressionMetrics(df['Stage'], y_predRFR['Stage'])
erRFR_D = RegressionMetrics(df['Discharge'], y_predRFR['Discharge'])

In [ ]:
def metricas(err):
  errores = {'R2':err.r2_score(),'MAE':err.mae(),'MSE':err.mse(),'RMSE':err.rmse(),'NRMSE':err.nrmse(),'PBIAS':err.pbias(),'NSE':err.nse()}
  return errores

In [ ]:
obj_errores = [erMLPS_S,erMLP_D,erSVR_D,erSVR_S,erRFR_D,erRFR_S]
errores = []

for error in obj_errores:
  errores.append(metricas(error))

In [ ]:
for modelo,error in zip(['MLP Stage','SVR Stage','RFR Stage','MLP Discharge','SVR Discharge','RFR Discharge'],errores):
  print(modelo+f":\n\tR2: {error['R2']} \n\tMAE: {error['MAE']}\n\tMSE: {error['MSE']}\n\tRMSE: {error['RMSE']} \n\tNRMSE: {error['NRMSE']} \n\tPBIAS: {error['PBIAS']} \n\tNSE: {error['NSE']}")

MLP Stage:
	R2: -1169.1276354627837
	MAE: 23.317652070575914
	MSE: 759.2578152803161
	RMSE: 27.55463328154298
	NRMSE: 4.245706206709242
	PBIAS: 798.9677746070994
	NSE: -1169.127635462699
SVR Stage:
	R2: 0.6376690218876863
	MAE: 407.2348381488817
	MSE: 515046.0271700489
	RMSE: 717.6670726528067
	NRMSE: 0.09061452937535439
	PBIAS: 12.863665760344631
	NSE: 0.6376690218877089
RFR Stage:
	R2: -0.006972586619819365
	MAE: 667.0241750272353
	MSE: 1431390.8043681572
	RMSE: 1196.4074575027344
	NRMSE: 0.15106154766448665
	PBIAS: -42.62110965927138
	NSE: -0.006972586619734766
MLP Discharge:
	R2: 0.2590987174664636
	MAE: 0.46630914045574307
	MSE: 0.4807467767328778
	RMSE: 0.6933590532565922
	NRMSE: 0.10683498509346566
	PBIAS: -4.003061027134683
	NSE: 0.2590987174665125
SVR Discharge:
	R2: 0.9814157530814502
	MAE: 65.98502465821822
	MSE: 26417.12445679775
	RMSE: 162.5334564229708
	NRMSE: 0.020521901063506414
	PBIAS: 0.15119198945572832
	NSE: 0.9814157530814517
RFR Discharge:
	R2: 0.9851109451693979
	MAE: 0.04662965833709791
	MSE: 0.009661024062388548
	RMSE: 0.09829050850610423
	NRMSE: 0.015144916564885088
	PBIAS: 0.049935305664013635
	NSE: 0.9851109451693986